(() => {
const $=id=>document.getElementById(id);let client;
function msg(t,err=false){$("loginMsg").textContent=t;$("loginMsg").style.color=err?"#ff6b8a":""}
async function init(){if(!window.supabase||!window.REFLORIA_SUPABASE_URL||window.REFLORIA_SUPABASE_URL.includes("YOUR_"))return msg("Supabase接続設定を確認してください。",true);client=window.supabase.createClient(window.REFLORIA_SUPABASE_URL,window.REFLORIA_SUPABASE_KEY);const {data}=await client.auth.getSession();if(data.session)show();else $("login").hidden=false}
async function login(e){e.preventDefault();$("loginBtn").disabled=true;const {error}=await client.auth.signInWithPassword({email:$("email").value.trim(),password:$("password").value});if(error)msg("ログインできません: "+error.message,true);else show();$("loginBtn").disabled=false}
function show(){$("login").hidden=true;$("app").hidden=false;$("logout").hidden=false;loadEvents();loadDrivers()}
$("logout").onclick=async()=>{await client.auth.signOut();location.reload()};$("loginBtn").onclick=login;
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("eventsPage").hidden=b.dataset.page!=="events";$("driversPage").hidden=b.dataset.page!=="drivers"});
async function loadEvents(){const {data,error}=await client.from("events").select("*").order("event_date",{ascending:true}).order("event_time",{ascending:true});if(error){$("eventList").textContent=error.message;return}$("eventList").innerHTML=(data||[]).map((e,i)=>`<div class="eventRow"><div><b>${i+1}. ${esc(e.event_name)}</b><span>${e.event_date} / ${String(e.event_time).slice(0,5)} / ${esc(e.event_location)}</span></div><button type="button" onclick="editEvent(${e.id})">編集</button><button type="button" class="danger" onclick="deleteEvent(${e.id})">削除</button></div>`).join("")||"<p>イベントがありません。</p>"}
async function editEvent(id){const {data}=await client.from("events").select("*").eq("id",id).single();if(!data)return; $("eventName").value=data.event_name;$("eventDate").value=data.event_date;$("eventTime").value=String(data.event_time).slice(0,5);$("eventLocation").value=data.event_location;$("eventHost").value=data.host||"";$("eventPrize").value=data.prize||"";$("eventDescription").value=data.description||"";$("driftOnly").checked=data.drift_only;$("tcsOff").checked=data.tcs_off;$("nonCustom").checked=data.non_custom;$("judgeReview").checked=data.judge_review;$("eventForm").dataset.editId=id;window.scrollTo({top:0,behavior:"smooth"})}
$("eventForm").onsubmit=async e=>{e.preventDefault();const p={event_name:$("eventName").value,event_date:$("eventDate").value,event_time:$("eventTime").value,event_location:$("eventLocation").value,host:$("eventHost").value,prize:$("eventPrize").value,description:$("eventDescription").value,drift_only:$("driftOnly").checked,tcs_off:$("tcsOff").checked,non_custom:$("nonCustom").checked,judge_review:$("judgeReview").checked,updated_at:new Date().toISOString()};const id=e.target.dataset.editId;const r=id?await client.from("events").update(p).eq("id",id):await client.from("events").insert(p);$("saveMsg").textContent=r.error?r.error.message:(id?"更新しました ✓":"追加しました ✓");e.target.reset();delete e.target.dataset.editId;loadEvents()};
window.deleteEvent=async id=>{if(confirm("このイベントを削除しますか？")){await client.from("events").delete().eq("id",id);loadEvents()}}
async function loadDrivers(){const {data,error}=await client.from("drivers").select("*").order("id");if(error)return $("driverList").textContent=error.message;$("driverList").innerHTML=(data||[]).map(d=>`<div class="driver"><b>${esc(d.name)}</b><span>${esc(d.car||"—")}</span><span>${esc(d.team||"—")}</span><button type="button" onclick="delDriver(${d.id})">削除</button></div>`).join("")||"<p>選手がまだいません。</p>"}
$("driverForm").onsubmit=async e=>{e.preventDefault();const r=await client.from("drivers").insert({name:$("driverName").value.trim(),car:$("driverCar").value.trim(),team:$("driverTeam").value.trim()});if(r.error)alert(r.error.message);else{e.target.reset();loadDrivers()}}
window.delDriver=async id=>{if(confirm("削除しますか？")){await client.from("drivers").delete().eq("id",id);loadDrivers()}}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
init();
})();